let products=JSON.parse(localStorage.getItem("store_products")||"[]");let currentImage="";const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat("ar-IQ").format(Number(n)||0)+" د.ع";
function save(){localStorage.setItem("store_products",JSON.stringify(products))}
function img(p){return p.image?`<img src="${p.image}" alt="">`:(p.icon||"🛍️")}
function stats(){ $("#statProducts").textContent=products.length;$("#statStock").textContent=products.reduce((a,p)=>a+(+p.stock||0),0);$("#statValue").textContent=money(products.reduce((a,p)=>a+(+p.price||0)*(+p.stock||0),0))}
function render(){let q=($("#adminSearch")?.value||"").trim().toLowerCase(),cat=$("#adminCat")?.value||"all";let list=products.filter(p=>(!q||p.name.toLowerCase().includes(q)||(p.sku||"").toLowerCase().includes(q))&&(cat==="all"||p.cat===cat));$("#adminRows").innerHTML=list.map(p=>`<tr><td><div class="prod-cell"><div class="thumb">${img(p)}</div><div><b>${p.name}</b><small style="display:block;color:#999">${p.description?.slice(0,35)||""}</small></div></div></td><td>${p.sku||"-"}</td><td>${p.category||p.cat}</td><td>${money(p.price)}</td><td>${p.stock||0}</td><td class="actions"><button onclick="edit(${p.id})">تعديل</button><button class="delete" onclick="del(${p.id})">حذف</button></td></tr>`).join("")||`<tr><td colspan="6" style="text-align:center;padding:35px">لا توجد منتجات</td></tr>`;stats()}
function resetForm(){["pName","pSku","pCategory","pPrice","pOld","pStock","pBadge","pDesc","editId"].forEach(id=>$("#"+id).value="");$("#pStock").value=0;currentImage="";$("#preview").innerHTML="📷";$("#formTitle").textContent="إضافة منتج"}
function openEditor(p=null){$("#productEditor").classList.add("show");if(!p){resetForm();return}$("#formTitle").textContent="تعديل المنتج";$("#editId").value=p.id;$("#pName").value=p.name;$("#pSku").value=p.sku||"";$("#pCat").value=p.cat;$("#pCategory").value=p.category||"";$("#pPrice").value=p.price;$("#pOld").value=p.old||"";$("#pStock").value=p.stock||0;$("#pBadge").value=p.badge||"";$("#pDesc").value=p.description||"";currentImage=p.image||"";$("#preview").innerHTML=p.image?`<img src="${p.image}">`:"📷"}
function edit(id){openEditor(products.find(p=>p.id===id))}
function del(id){if(confirm("حذف المنتج؟")){products=products.filter(p=>p.id!==id);save();render()}}
$("#addBtn").onclick=()=>openEditor();$("#closeEditor").onclick=$("#cancelEditor").onclick=()=>$("#productEditor").classList.remove("show");
$("#imageFile").onchange=e=>{let file=e.target.files[0];if(!file)return;if(file.size>2.5*1024*1024){alert("الصورة كبيرة. اختر صورة أقل من 2.5MB.");e.target.value="";return}let r=new FileReader();r.onload=()=>{currentImage=r.result;$("#preview").innerHTML=`<img src="${currentImage}">`};r.readAsDataURL(file)};
$("#productForm").onsubmit=e=>{e.preventDefault();let id=+$("#editId").value||Date.now(),old=products.find(p=>p.id===id);let p={id,name:$("#pName").value.trim(),sku:$("#pSku").value.trim(),cat:$("#pCat").value,category:$("#pCategory").value.trim()||$("#pCat option:checked").textContent,price:+$("#pPrice").value,old:$("#pOld").value?+$("#pOld").value:null,stock:+$("#pStock").value,badge:$("#pBadge").value.trim(),description:$("#pDesc").value.trim(),image:currentImage,icon:old?.icon||"🛍️"};let i=products.findIndex(x=>x.id===id);i>=0?products[i]=p:products.unshift(p);save();render();$("#productEditor").classList.remove("show")};
$("#adminSearch").oninput=render;$("#adminCat").onchange=render;
document.querySelectorAll(".side").forEach(b=>b.onclick=()=>{document.querySelectorAll(".side").forEach(x=>x.classList.remove("active"));b.classList.add("active");let p=b.dataset.page;$("#productsPage").classList.toggle("hidden",p!=="products");$("#settingsPage").classList.toggle("hidden",p!=="settings")});
let settings=JSON.parse(localStorage.getItem("store_settings")||"{}");if(settings.name)$("#storeName").value=settings.name;if(settings.wa)$("#waNumber").value=settings.wa;if(settings.desc)$("#storeDesc").value=settings.desc;$("#saveSettings").onclick=()=>{localStorage.setItem("store_settings",JSON.stringify({name:$("#storeName").value,wa:$("#waNumber").value,desc:$("#storeDesc").value}));alert("تم حفظ الإعدادات")};
render();
