const products=[
{id:1,name:"سماعة لاسلكية Pro",cat:"electronics",category:"إلكترونيات",price:35000,old:45000,icon:"🎧",badge:"خصم"},
{id:2,name:"ساعة ذكية X8",cat:"electronics",category:"إلكترونيات",price:55000,old:70000,icon:"⌚",badge:"عرض"},
{id:3,name:"خلاط مطبخ متعدد",cat:"home",category:"منزل",price:28000,old:35000,icon:"🥤",badge:"خصم"},
{id:4,name:"مصباح مكتبي LED",cat:"home",category:"منزل",price:18000,old:null,icon:"💡",badge:""},
{id:5,name:"حقيبة يومية أنيقة",cat:"fashion",category:"أزياء",price:25000,old:32000,icon:"👜",badge:"خصم"},
{id:6,name:"نظارة شمسية كلاسيكية",cat:"fashion",category:"أزياء",price:22000,old:null,icon:"🕶️",badge:""},
{id:7,name:"شاحن سريع 33W",cat:"electronics",category:"إلكترونيات",price:12000,old:15000,icon:"🔌",badge:"جديد"},
{id:8,name:"طقم أكواب أنيق",cat:"home",category:"منزل",price:16000,old:null,icon:"☕",badge:""}
];
const categories=[["all","✨","كل المنتجات"],["electronics","📱","إلكترونيات"],["home","🏠","المنزل"],["fashion","👕","أزياء"]];
let cart=JSON.parse(localStorage.getItem("cart")||"[]"), filter="all";
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat("ar-IQ").format(n)+" د.ع";
function save(){localStorage.setItem("cart",JSON.stringify(cart));renderCart()}
function renderCategories(){ $("#categoryList").innerHTML=categories.map(c=>`<div class="category" data-cat="${c[0]}"><span class="cat-icon">${c[1]}</span><strong>${c[2]}</strong></div>`).join("");document.querySelectorAll(".category").forEach(x=>x.onclick=()=>{filter=x.dataset.cat;renderProducts();location.hash="products"})}
function renderProducts(list=products.filter(p=>filter==="all"||p.cat===filter)){ $("#productGrid").innerHTML=list.length?list.map(p=>`<article class="product"><div class="product-img" data-view="${p.id}">${p.icon}</div>${p.badge?`<span class="badge">${p.badge}</span>`:""}<div class="product-info"><h3>${p.name}</h3><p>${p.category}</p><div class="price">${money(p.price)} ${p.old?`<span class="old">${money(p.old)}</span>`:""}</div><button class="add" data-add="${p.id}">أضف إلى السلة</button></div></article>`).join(""):"<p>لا توجد منتجات.</p>";document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>add(+b.dataset.add));document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>view(+b.dataset.view))}
function add(id){let x=cart.find(i=>i.id===id);x?x.qty++:cart.push({id,qty:1});save();openCart()}
function renderCart(){let count=cart.reduce((a,i)=>a+i.qty,0);$("#cartCount").textContent=count;let total=0;$("#cartItems").innerHTML=cart.length?cart.map(i=>{let p=products.find(x=>x.id===i.id);total+=p.price*i.qty;return `<div class="cart-row"><div class="cart-thumb">${p.icon}</div><div><h4>${p.name}</h4><small>${money(p.price)}</small><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${i.qty}</b><button onclick="changeQty(${p.id},1)">+</button></div></div><b>${money(p.price*i.qty)}</b></div>`}).join(""):`<div style="text-align:center;color:#888;padding:60px 10px">السلة فارغة 🛒</div>`;$("#cartTotal").textContent=money(total)}
function changeQty(id,n){let x=cart.find(i=>i.id===id);if(!x)return;x.qty+=n;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);save()}
function openCart(){$("#cartDrawer").classList.add("open");$("#overlay").classList.add("show")}
function closeCart(){$("#cartDrawer").classList.remove("open");$("#overlay").classList.remove("show")}
function view(id){let p=products.find(x=>x.id===id);$("#modalContent").innerHTML=`<div class="modal-img">${p.icon}</div><div class="modal-body"><span class="eyebrow">${p.category}</span><h2>${p.name}</h2><p>منتج مختار بعناية. يمكنك إضافته إلى السلة ثم إدخال معلومات التوصيل عند إتمام الطلب.</p><h3>${money(p.price)} ${p.old?`<span class="old">${money(p.old)}</span>`:""}</h3><button class="primary-btn full" onclick="add(${p.id});document.querySelector('dialog').close()">أضف إلى السلة</button></div>`;$("#productModal").showModal()}
document.addEventListener("DOMContentLoaded",()=>{renderCategories();renderProducts();renderCart();document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;renderProducts()});$("#cartBtn").onclick=openCart;$("#closeCart").onclick=closeCart;$("#overlay").onclick=closeCart;$("#clearCart").onclick=()=>{cart=[];save()};$("#closeModal").onclick=()=>$("#productModal").close();$("#menuBtn").onclick=()=>$("#mainNav").classList.toggle("show");$("#searchBtn").onclick=()=>{$("#searchPanel").classList.add("show");$("#searchInput").focus()};$("#closeSearch").onclick=()=>$("#searchPanel").classList.remove("show");$("#searchInput").oninput=e=>{let q=e.target.value.trim();renderProducts(q?products.filter(p=>p.name.includes(q)||p.category.includes(q)):products.filter(p=>filter==="all"||p.cat===filter))};$("#checkoutBtn").onclick=()=>{if(!cart.length)return alert("السلة فارغة");$("#checkoutModal").classList.add("show");closeCart()};$("#closeCheckout").onclick=()=>$("#checkoutModal").classList.remove("show");$("#checkoutForm").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),lines=cart.map(i=>{let p=products.find(x=>x.id===i.id);return `${p.name} × ${i.qty} = ${money(p.price*i.qty)}`}).join("\\n");let msg=`طلب جديد من المتجر\\n\\nالاسم: ${f.get("name")}\\nالهاتف: ${f.get("phone")}\\nالمحافظة: ${f.get("city")}\\nالعنوان: ${f.get("address")}\\nملاحظات: ${f.get("note")||"-"}\\n\\nالمنتجات:\\n${lines}\\n\\nالمجموع: ${$("#cartTotal").textContent}`;window.open("https://wa.me/9647700000000?text="+encodeURIComponent(msg),"_blank");};});
